<?php 

/**
 * Plugin Name:       Admin Login Monitor
 * Plugin URI:        https://github.com/jackfischer/Wordpress-Admin-Login-Monitor
 * Description:       Automatically email warning for new admin logins
 * Version:           1.1.0
 * Author:            Jack Fischer
 * Author URI:        https://github.com/jackfischer
 * License:           GPL v2 or later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 */


class JFAdminLoginMonitor {

  private static function get_forwarded_ip() {
    foreach (array('HTTP_CLIENT_IP', 'HTTP_X_FORWARDED_FOR', 'HTTP_X_FORWARDED', 'HTTP_X_CLUSTER_CLIENT_IP', 'HTTP_FORWARDED_FOR', 'HTTP_FORWARDED', 'REMOTE_ADDR') as $key) {
      if (array_key_exists($key, $_SERVER) === true) {
        foreach (array_map('trim', explode(',', $_SERVER[$key])) as $ip) {
          if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) !== false) {
            return [$key, $ip];
          }
        }
      }
    }
  }

  public static function process_admin_login( $user_login, $user ) {
    if (current_user_can( 'administrator' )) {
      return;
    }

    $site = get_bloginfo("name");
    $subject = "[{$site}] Admin Login: {$user_login}";
    $headers = array('Content-Type: text/html; charset=UTF-8');
    $user_edit_link = admin_url('user-edit.php') . "?user_id={$user->ID}";

    [$forwarded_header, $forwarded_ip] = self::get_forwarded_ip();

    $admins = get_users( array( 'role' => 'administrator' ) );
    foreach ($admins as $admin) {
      $email = $admin->user_email;

      // TODO https://stackoverflow.com/a/20720053/4922673
      $message = "
<html>
<body>
Hello {$admin->display_name},

The account '<b>{$user->user_nicename}</b>' just logged in.

<div style='font-family: monospace;'>
User Login '<a href='{$user_edit_link}'>{$user->user_login}</a>'
User Display Name '<a href='{$user_edit_link}'>{$user->display_name}</a>'
User Email {$user->user_email}
User ID '<a href='{$user_edit_link}'>{$user->ID}</a>'
User Registered {$user->user_registered}

Forwarded IP Address <a href='https://ipinfo.io/{$forwarded_ip}'>{$forwarded_ip}</a> (${forwarded_header})
Connected IP Address <a href='https://ipinfo.io/{$_SERVER['REMOTE_ADDR']}'>{$_SERVER['REMOTE_ADDR']}</a> (possibly a CDN or proxy)

{$_SERVER['HTTP_USER_AGENT']}
</div>

<footer style='opacity: 75%;'>
This notification is generated by the Wordpress Admin Login Monitor plugin.

This email links to <a href='https://ipinfo.io'>ipinfo.io</a>. See ipinfo.io <a href='https://ipinfo.io/terms-of-service'>Terms of Service</a> and <a href='https://ipinfo.io/privacy-policy'>Privacy Policy</a>
</footer>
</body>
</html>
";

      $html_friendly_message = nl2br($message);
      wp_mail($email, $subject, $html_friendly_message, $headers);
    }
  }

}

add_action( 'wp_login', 'JFAdminLoginMonitor::process_admin_login', 10, 2 );

?>
