<?php 

/**
 * Plugin Name:       Admin Login Monitor
 * Plugin URI:        https://github.com/jackfischer/Wordpress-Admin-Login-Monitor
 * Description:       Automatically email warning for new admin logins
 * Version:           1.2.0
 * Author:            Jack Fischer
 * Author URI:        https://github.com/jackfischer
 * License:           GPL v2 or later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 */


class JFAdminLoginMonitor {

  private static function get_forwarded_ip() {
    foreach (array('HTTP_CLIENT_IP', 'HTTP_X_FORWARDED_FOR', 'HTTP_X_FORWARDED', 'HTTP_X_CLUSTER_CLIENT_IP', 'HTTP_FORWARDED_FOR', 'HTTP_FORWARDED', 'HTTP_CF_CONNECTING_IP', 'X-FORWARDED-FOR', 'CF-CONNECTING-IP') as $key) {
      if (array_key_exists($key, $_SERVER) === true) {
        foreach (array_map('trim', explode(',', sanitize_text_field($_SERVER[$key]))) as $ip) {
          if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) !== false) {
            return [$key, $ip];
          }
        }
      }
    }
    return ['None', 'No forwarded IP headers'];
  }

  public static function process_admin_login( $user_login, $user ) {
    if (current_user_can( 'administrator' )) { // Non-administrator logging in
      return;
    }

    $site = get_bloginfo("name");
    $subject = "[{$site}] Admin Login: {$user_login}";
    $headers = array('Content-Type: text/html; charset=UTF-8');
    $user_edit_link = admin_url('user-edit.php') . "?user_id={$user->ID}";

    [$forwarded_header, $forwarded_ip] = self::get_forwarded_ip();

    $admins = get_users( array( 'role' => 'administrator' ) );
    foreach ($admins as $admin) {
      $email = $admin->user_email;

      // TODO https://stackoverflow.com/a/20720053/4922673
      $remoteAddr = sanitize_text_field($_SERVER['REMOTE_ADDR']);
      $userAgent = sanitize_text_field($_SERVER['HTTP_USER_AGENT']);
      $message = "
<html>
<body>
Hello ".esc_html($admin->display_name).",

The account '<b>".esc_html($user->user_nicename)."</b>' just logged into ".$site.".

<div style='font-family: monospace;'>
User Login '<a href='" . esc_url($user_edit_link) . "'>" . esc_html($user->user_login) . "</a>'
User Display Name '<a href='". esc_url($user_edit_link) . "'>" . esc_html($user->display_name) . "</a>'
User Email ".esc_html($user->user_email)."
User ID '<a href='".esc_url($user_edit_link)."'>".esc_html($user->ID)."</a>'
User Registered ".esc_html($user->user_registered)."

Forwarded IP Address <a href='https://ipinfo.io/".$forwarded_ip."'>".esc_html($forwarded_ip)."</a> (".esc_html($forwarded_header).")
Connected IP Address <a href='https://ipinfo.io/".esc_url($remoteAddr)."'>".esc_html($remoteAddr)."</a> (possibly a CDN or proxy)

".esc_html($userAgent)."
</div>

<footer style='opacity: 70%;'>
This notification is generated by the Wordpress Admin Login Monitor plugin installed on ".esc_html($site)."
</footer>
</body>
</html>
";

      $html_friendly_message = nl2br($message);
      wp_mail($email, $subject, $html_friendly_message, $headers);
    }
  }

}

add_action( 'wp_login', 'JFAdminLoginMonitor::process_admin_login', 10, 2 );

?>
