<?php 

/**
 * Plugin Name:       Admin Login Monitor
 * Plugin URI:        https://github.com/jackfischer/Wordpress-Admin-Login-Monitor
 * Description:       Automatically email warning for new admin logins
 * Version:           1.0.1
 * Author:            Jack Fischer
 * Author URI:        https://github.com/jackfischer
 * License:           GPL v2 or later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 */

if ( !class_exists( 'JFAdminLoginMonitor' ) ) {

  class JFAdminLoginMonitor {
    function __construct() {
      add_action('wp_login', [$this, 'process_admin_login']);
    }

    private static function get_forwarded_ip() {
      foreach (array('HTTP_CLIENT_IP', 'HTTP_X_FORWARDED_FOR', 'HTTP_X_FORWARDED', 'HTTP_X_CLUSTER_CLIENT_IP', 'HTTP_FORWARDED_FOR', 'HTTP_FORWARDED', 'REMOTE_ADDR') as $key) {
        if (array_key_exists($key, $_SERVER) === true) {
          foreach (array_map('trim', explode(',', $_SERVER[$key])) as $ip) {
            if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) !== false) {
              return [$key, $ip];
            }
          }
        }
      }
    }

    public static function process_admin_login( $user_login, $user ) {
      if (!in_array('administrator',  wp_get_current_user()->roles)) {
        return;
      }

      $site = get_bloginfo("name");
      $subject = "[{$site}] Admin Login: {$user_login}";
      $headers = array('Content-Type: text/html; charset=UTF-8');
      $user_edit_link = admin_url('user-edit.php') . "?user_id={$user->ID}";
      [$forwarded_header, $forwarded_ip] = get_forwarded_ip();

      $admins = get_users( array( 'role' => 'administrator' ) );
      foreach ($admins as $admin) {
        $email = $admin->user_email;

        $message = "
Hello {$admin->display_name},

The account '{$user->user_nicename}' just logged in.

User Login <a href='{$user_edit_link}'>'{$user->user_login}'</a>
User Display Name '{$user->display_name}'
User Email {$user->user_email}
User ID {$user->ID}
User Registered {$user->user_registered}

Forwarded IP Address <a href='https://ipinfo.io/{$forwarded_ip}'>{$forwarded_ip}</a> ('${forwarded_header}')
Connected IP Address <a href='https://ipinfo.io/{$_SERVER['REMOTE_ADDR']}'>{$_SERVER['REMOTE_ADDR']}</a>
{$_SERVER['HTTP_USER_AGENT']}

This notification is generated by the Wordpress Admin Login Monitor plugin.
";

        $html_friendly_message = nl2br($message);
        wp_mail($email, $subject, $html_friendly_message, $headers);
      }
    }

  }

}

?>
